server:
  port: 8081

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI} #mongodb://mongo:27017/customer-db  #localhost



eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/ #registry-service



