server:
  port: 8085

spring:
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    host: mongo
    port: 27017
    database: customer-db



eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/ #registry-service



