server:
  port: 8080

spring:
  cloud:
    gateway:

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: customer-service
          uri: http://customer-service/
          predicates:
            - Path=/customer-service/**
          filters:
            - StripPrefix=1
        - id: passive-product-service
          uri: http://passive-product-service/
          predicates:
            - Path=/passive-product-service/**
          filters:
            - StripPrefix=1
        - id: active-product-service
          uri: http://active-product-service/
          predicates:
            - Path=/active-product-service/**
          filters:
            - StripPrefix=1

# ======================================================
# ✅ CIRCUIT BREAKERS (Resilience4j)
# ======================================================
resilience4j:
  circuitbreaker:
    instances:
      customerCB:
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 8s
        permittedNumberOfCallsInHalfOpenState: 3

      passiveCB:
        slidingWindowSize: 15
        failureRateThreshold: 60
        waitDurationInOpenState: 6s

      activeCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s


# ======================================================
# ✅ LOGS ESTRUCTURADOS (Logstash JSON Encoder)
# ======================================================
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/
