
server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/
