
server:
  port: 8084

app:
  server:
    gateway: http://localhost:8080

spring:
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    host: localhost
    port: 27017
    database: movement-service-db

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081

    admin:
      properties:
        bootstrap.servers: localhost:9092
      fail-fast: true
      auto-create: true

    topics:
      movement-requested:
        partitions: 3
        replicas: 1
      movement-completed:
        partitions: 3
        replicas: 1
      movement-rejected:
        partitions: 3
        replicas: 1

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      specific-avro-reader: true





resilience4j:
  circuitbreaker:
    instances:
      customerService:
        slidingWindowSize: 10
        failureRateThreshold: 60
        waitDurationInOpenState: 10s

  retry:
    instances:
      customerService:
        maxAttempts: 3
        waitDuration: 500ms

  timelimiter:
    instances:
      customerService:
        timeoutDuration: 2s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #registry-service
