server:
  port: 8082

app:
  server:
    gateway: http://localhost:8080

spring:
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    host: localhost
    port: 27017
    database: passive-product-service-db

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
      metadata.max.age.ms: 10000
      metadata.fetch.timeout.ms: 30000

    producer:
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        retry.backoff.ms: 2000
        request.timeout.ms: 30000
        delivery.timeout.ms: 60000

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer




resilience4j:
  circuitbreaker:
    instances:
      customerService:
        slidingWindowSize: 10
        failureRateThreshold: 60
        waitDurationInOpenState: 10s

  retry:
    instances:
      customerService:
        maxAttempts: 3
        waitDuration: 500ms

  timelimiter:
    instances:
      customerService:
        timeoutDuration: 2s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #registry-service
